#!/bin/bash
ShowMenu() {
    echo -e "$LOGO"
    echo -e "     $B_BLUE                      $PROJECT_TITLE PROJECT -> $CONTAINER $NC$B_BLUE               $NC"
    echo ""
    echo -e "          [0] Executar comandos de compilação"
    echo -e "          [1] Verificar pacotes necessários"
    echo -e "          [2] Inicializar containers $CONTAINER"
    echo -e "          [3] Pausar containers $CONTAINER"
    echo -e "          [4] Realizar Dump $CONTAINER"
    echo -e "          [5] Acessar container via ssh"
    echo -e "          [6] Clonar Projeto"
    echo -e "          [7] Adicionar loja /etc/hosts"
    echo -e "          [8] Configurar env & docker-compose"
    echo -e "          [9] Instalar o grunt"
    echo -e "          [10] Executar o grunt"
    echo -e "          [11] Alterar senha dos customers"
    echo -e "          [12] Alterar todas as bases urls"
    echo -e "          [13] Desabilitar módulos auth admin"
    echo -e "          [14] Change Project"
    echo -e "          [15] Executar cron"
    echo -e "          [16] Limpeza de tabelas de log"
    echo -e "          [17] Fazer Backup Banco e Projeto"
    echo -e " $B_RED         [99] Zerar todo o docker  $NC"
    echo -e "     $B_BLUE                      $PROJECT_TITLE PROJECT -> $CONTAINER $NC$B_BLUE               $NC"
}
